"""Constantes de contrato de variables de entorno para VASQUEZ."""

from __future__ import annotations

# Variables de entorno leídas por libvasquez_inject.so
ENV_MALLOC_FAIL_AT = "VASQUEZ_MALLOC_FAIL_AT"
ENV_CALLOC_FAIL_AT = "VASQUEZ_CALLOC_FAIL_AT"
ENV_REALLOC_FAIL_AT = "VASQUEZ_REALLOC_FAIL_AT"
ENV_POSIX_MEMALIGN_FAIL_AT = "VASQUEZ_POSIX_MEMALIGN_FAIL_AT"
ENV_MALLOC_PROB = "VASQUEZ_MALLOC_PROB"
ENV_CASCADE_FAILS = "VASQUEZ_CASCADE_FAILS"
ENV_GARBAGE_MEMORY = "VASQUEZ_GARBAGE_MEMORY"
ENV_POISON_BYTE = "VASQUEZ_POISON_BYTE"
ENV_FOPEN_FAIL_AT = "VASQUEZ_FOPEN_FAIL_AT"
ENV_ERRNO = "VASQUEZ_ERRNO"
ENV_FAIL_WRITE_AFTER_BYTES = "VASQUEZ_FAIL_WRITE_AFTER_BYTES"
ENV_FREAD_FAIL_AT = "VASQUEZ_FREAD_FAIL_AT"
ENV_FCLOSE_FAIL_AT = "VASQUEZ_FCLOSE_FAIL_AT"
ENV_TRACE = "VASQUEZ_TRACE"
ENV_TRACE_FILE = "VASQUEZ_TRACE_FILE"
